(deftheme monochrome-bright
  "Created 2018-03-13.")

(custom-theme-set-variables
 'monochrome-bright
 '(ansi-color-names-vector ["white" "#303030" "#b3b3b3" "#606060"]))

(custom-theme-set-faces
 'monochrome-bright
 '(cursor ((((class color) (min-colors 10)) (:background "black"))))
 '(fringe ((((class color) (min-colors 10)) (:foreground "white" :background "#303030"))))
 '(highlight ((((class color) (min-colors 10)) (:foreground "white" :background "#606060"))))
 '(region ((((class color) (min-colors 10)) (:foreground "white" :background "#303030"))))
 '(secondary-selection ((((class color) (min-colors 10)) (:foreground: "white" :background "#606060"))))
 '(isearch ((((class color) (min-colors 10)) (:foreground "white" :background "#303030"))))
 '(lazy-highlight ((((class color) (min-colors 10)) (:foreground "white" :background "#303030"))))
 '(trailing-whitespace ((((class color) (min-colors 10)) (:background "red"))))
 '(mode-line ((((class color) (min-colors 10)) (:box (:line-width -1 :style released-button) :background "#e5e5e5" :foreground "#303030"))))
 '(mode-line-inactive ((((class color) (min-colors 10)) (:box (:line-width -1 :style released-button) :background "#b0b0b0" :foreground "black"))))
 '(whitespace-empty ((((class color) (min-colors 10)) (:background unspecified :foreground "red"))))
 '(whitespace-line ((((class color) (min-colors 10)) (:background "#b3b3b3" :foreground "black"))))
 '(minibuffer-prompt ((((class color) (min-colors 10)) (:weight bold :foreground "#303030"))))
 '(escape-glyph ((((class color) (min-colors 10)) (:foreground "#303030"))))
 '(error ((((class color) (min-colors 10)) (:background "#303030" :weight bold :slant italic :foreground "red"))))
 '(warning ((((class color) (min-colors 10)) (:background "#303030" :foreground "yellow"))))
 '(success ((((class color) (min-colors 10)) (:background "#303030" :foreground "green"))))
 '(font-lock-builtin-face ((((class color) (min-colors 10)) (:foreground "#303030"))))
 '(font-lock-comment-face ((((class color) (min-colors 10)) (:slant italic :foreground "#b3b3b3"))))
 '(font-lock-constant-face ((((class color) (min-colors 10)) (:weight bold :foreground "#303030"))))
 '(font-lock-function-name-face ((((class color) (min-colors 10)) (:foreground "black"))))
 '(font-lock-keyword-face ((((class color) (min-colors 10)) (:weight bold :foreground "black"))))
 '(font-lock-string-face ((((class color) (min-colors 10)) (:foreground "#606060"))))
 '(font-lock-type-face ((((class color) (min-colors 10)) (:weight bold :foreground "#303030"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 10)) (:weight bold :foreground "#b3b3b3"))))
 '(font-lock-warning-face ((((class color) (min-colors 10)) (:foreground "yellow"))))
 '(link ((((class color) (min-colors 10)) (:underline t :foreground "#303030"))))
 '(link-visited ((((class color) (min-colors 10)) (:underline t :foreground "#303030"))))
 '(show-paren-match ((t (:background "#606060"))))
 '(show-paren-mismatch ((t (:background "red"))))
 '(ido-first-match ((((class color) (min-colors 10)) (:foreground "#303030"))))
 '(ido-only-match ((((class color) (min-colors 10)) (:underline "#303030" :foreground "#303030"))))
 '(ido-subdir ((((class color) (min-colors 10)) (:weight bold :foreground "black"))))
 '(message-header-name ((((class color) (min-colors 10)) (:foreground "#303030"))))
 '(message-header-cc ((((class color) (min-colors 10)) (:foreground "#303030"))))
 '(message-header-other ((((class color) (min-colors 10)) (:foreground "#303030"))))
 '(message-header-subject ((((class color) (min-colors 10)) (:foreground "#303030"))))
 '(message-header-to ((((class color) (min-colors 10)) (:weight bold :foreground "#303030"))))
 '(message-cited-text ((((class color) (min-colors 10)) (:slant italic :foreground "#303030"))))
 '(message-separator ((((class color) (min-colors 10)) (:weight bold :foreground "#303030"))))
 '(org-level-1 ((t (:bold t :foreground "#303030" :height 1.5))))
 '(org-level-2 ((t (:bold nil :foreground "#303030" :height 1.2))))
 '(org-level-3 ((t (:bold t :foreground "#303030" :height 1.0))))
 '(org-level-4 ((t (:bold nil :foreground "#303030" :height 1.0))))
 '(org-link ((t (:foreground "#606060" :underline t))))
 '(org-todo ((t (:bold t :foreground "red"))))
 '(org-done ((t (:bold t :foreground "green"))))
 '(default ((t (:background "#fdf6e3" :foreground "black")))))

(provide-theme 'monochrome-bright)
